[project]
name = 'example'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.my-contract]
path = 'contracts/my-contract.clar'
clarity_version = 2
epoch = 2.4

[contracts.my-contract_test]
path = 'tests/my-contract_test.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
